### ISSUE TITLE
Clang warning in unique_resource

### ISSUE THREAD

**Issue by Pesa** [martinmoene/scope-lite#2]
This is reproducible with various versions of clang.

```
.../nonstd/scope-lite.hpp:909:33: warning: cannot refer to a non-static member from the handler of a constructor function try block [-Wexceptions]
            other.get_deleter()(get());
                                ^
1 warning generated.
```

**Comment by martinmoene** [comment]
Thanks Davide, will be a few weeks until I'm able to work on this & other issue(s) as I'm currently on holidays.

**Comment by Pesa** [comment]
I tested as of commit 203cce7e07653fda00b133e482c8283a322fc94f and the warning is gone. Thanks!
