### ISSUE TITLE
Incompatible declaration of __cxa_get_globals?

### ISSUE THREAD

**Issue by Pesa** [martinmoene/scope-lite#3]
It seems that `__cxa_get_globals()` is non-throwing from what I can see [here](https://libcxxabi.llvm.org/spec.html) and [here](https://github.com/gcc-mirror/gcc/blob/2ba0674c657fb2089d8aae4f8c254ce0559c8f53/libstdc%2B%2B-v3/libsupc%2B%2B/cxxabi.h#L605). However, the declaration of `__cxa_get_globals` in scope-lite does not contain an exception specification, so Clang (on macOS) complains that it "does not match the previous declaration".

**Comment by Pesa** [comment]
For reference, [this](https://github.com/boostorg/core/blob/develop/include/boost/core/uncaught_exceptions.hpp) is the Boost implementation. From the comments in that file the situation seems quite... messy.

**Comment by Pesa** [comment]
As of commit 12748b10388ba5e6d882759eccb258e9b09fcb40, clang on macOS still fails with

```
[...]/scope-lite.hpp:327:23: error: functions that differ only in their return type cannot be overloaded
    extern "C" char * __cxa_get_globals() scope_noexcept;
               ~~~~~~ ^
/usr/local/include/boost/core/uncaught_exceptions.hpp:75:30: note: previous declaration is here
extern "C" __cxa_eh_globals* __cxa_get_globals() BOOST_NOEXCEPT_OR_NOTHROW __attribute__((__const__));
           ~~~~~~~~~~~~~~~~~ ^
1 error generated.
```

As I said above, this is a conflict with a boost header, so you may choose to ignore the problem. It'd be great if it could be fix though, for a better out-of-the-box experience.

**Comment by Pesa** [comment]
> @mbeutel, I wasn't sure to do the complete dance from [the Boost implementation](https://github.com/boostorg/core/blob/develop/include/boost/core/uncaught_exceptions.hpp) to detect if `<cxxabi.h>` is available **and** still handle the situation where `__cxa_get_globals()` is not declared.

Fair enough, although that's a problem only if you care about gcc versions *older than* 4.7. If you can assume 4.7 or later, then `<cxxabi.h>` always declares `__cxa_get_globals()`, according to the comments in the Boost implementation.

**Comment by martinmoene** [comment]
> As of commit [12748b1](https://github.com/martinmoene/scope-lite/commit/12748b10388ba5e6d882759eccb258e9b09fcb40), clang on macOS still fails with
> 
> ```
> [...]/scope-lite.hpp:327:23: error: functions that differ only in their return type cannot be overloaded
>     extern "C" char * __cxa_get_globals() scope_noexcept;
>                ~~~~~~ ^
> /usr/local/include/boost/core/uncaught_exceptions.hpp:75:30: note: previous declaration is here
> extern "C" __cxa_eh_globals* __cxa_get_globals() BOOST_NOEXCEPT_OR_NOTHROW __attribute__((__const__));
>            ~~~~~~~~~~~~~~~~~ ^
> 1 error generated.
> ```
> 
> As I said above, this is a conflict with a boost header, so you may choose to ignore the problem. It'd be great if it could be fixed though, for a better out-of-the-box experience.

@Pesa Do you have a suggestion to avoid the conflict with Boost?

**Comment by Pesa** [comment]
> @Pesa Do you have a suggestion to avoid the conflict with Boost?

Something like 203cce7e07653fda00b133e482c8283a322fc94f is what I had in mind. Essentially the "fallback" declaration should use `__cxa_eh_globals*`, not `char*`. (where does the `char*` come from btw?)

**Comment by Pesa** [comment]
As of commit 203cce7e07653fda00b133e482c8283a322fc94f I can confirm that the following toolchain combinations compile with no warnings:
* gcc 5 and later on Linux
* clang 4 and later on Linux with libstdc++
* Apple clang/Xcode 9 and later on macOS

I have not extensively tested with clang/libc++ on Linux, but it seems to work on godbolt.

Still fails on FreeBSD 11 with clang.

**Comment by Pesa** [comment]
Commit cf39fd7071d90b2620b6675aa90da325caba195f does not fix the problem on FreeBSD, it seems only OpenBSD is handled.

**Comment by martinmoene** [comment]
> Commit [cf39fd7](https://github.com/martinmoene/scope-lite/commit/cf39fd7071d90b2620b6675aa90da325caba195f) does not fix the problem on FreeBSD, it seems only OpenBSD is handled.

...hope i'll get there in the end...

**Comment by Pesa** [comment]
Thanks. Commit 197cd4240069b2b8c393ad0d9eabdee601b606b4 seems to work fine on FreeBSD 11 and 12. I consider this issue closed as far as I'm concerned.

One minor observation: on FreeBSD `<cxxabi.h>` always provides a declaration for `__cxa_get_globals`, so we could include the header and simply rely on that declaration, similarly to the gcc case (note that it's not the same header, FreeBSD uses libcxxrt as far as I know).

**Comment by martinmoene** [comment]
Thanks for your help and perseverance.

Re: FreeBSD, I'll refrain from including its own header for now, one reason being I cannot easily test scenarios with FreeBSD myself.
